name: env_g
description: tool to generate dart file from env file
version: 1.0.1-beta
repository: https://github.com/ibrahemDev/env_g

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  tuple: ^2.0.2
  encrypt: ^5.0.1
  dart_style: ^2.3.2
  path: ^1.8.3
  convert: ^3.1.1
  freezed_annotation: ^2.4.1
  yaml: ^3.1.2
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1




